### ISSUE TITLE
Figure overview

### ISSUE THREAD

**Issue by erwinlambert** [AJueling/melt#18]
Fig 1: Schematic overview of models, increasing complexity. 3-5 panels (M, PICO, plume, PICOp, Layer, (MITgcm))
_Can introduce a colorscheme for the models here to be used throughout in lineplots and for subplot titles/borders_

Fig 2: Spatial ISOMIP. 4x2 panels. _Or 3x3 with one panel for 2 colorbars_

- 1: Geometry + inset forcing + marked grounding zone
- 2-8: models

Fig 3: Sensitivity ISOMIP. 3 panels.

- 1: Average melt vs deep T
- 2: Melt sensitivity vs deep T
- 3: Grounding zone melt vs deep T. _Alternative: max melt, 95th percentile, ..._

Fig 4: Validation PineIsland warm. 3x3 panels

- 1: Geometry + inset forcing tanh2(ztcl=-400,Tdeep=1.2). _Perhaps also show Dutrieux14 profiles for that period._
- 2: Observations from Shean
- 3: Colorbars
- 4-9: Models (M+, PICO, plume, PICOp, Layer, MITgcm). _MITgcm as validation or part of model hierarchy?_

Fig 5: Validation Dotson cold. 3x3 panels. _Could be moved to appendix/SI_

- 1: Geometry + inset forcing tanh2(ztcl=-700,Tdeep=.7). _Perhaps also show Jenkins18 profiles._
- 2: Observations from Gourmelen
- 3: Colorbars
- 4-9: Same as Fig 4

Fig 6: Amundsen Sea cold period. 3x2 panels. _If including Getz, stack 6 horizontal panels_
_Forcing: PIG,Thwaites: tanh2(ztcl=-600,Tdeep=1.2). CrossDots (and Getz): tanh2(ztcl=-700,Tdeep=.7)_

- 1-5: Models (M+, PICO, plume, PICOp, Layer)
- 6: MITgcm _2013-2017= cold period in model_

Fig 7: Amundsen Sea warm-cold. 3x2 panels.
_Forcing: PIG,Thwaites: tanh2(ztcl=-400,Tdeep=1.2). CrossDots (and Getz): tanh2(ztcl=-400,Tdeep=.7)_

- 1-5: Models (M+, PICO, plume, PICOp, Layer)
- 6: MITgcm _2008-2012= cold period in model_

**Comment by AJueling** [comment]
(Figure numbering as suggested above)

@erwinlambert 
- [ ] check validation whether melt rate given as  ice or water
- [ ] final tuning for Layer
- [x] rerun all simulations
- [x] commit Figs. 4/5 code
- [x] create Fig 6,7 code
- [ ] send all the data
- [ ] tuning section 2.5 to methods: describe Layer procedure

@AJueling 
- [ ] tuning aim for reasonable COLD/WARM/WARM-COLD rates PineIsland and Crosson/Dotson, write about this in tuning section
- [ ] check negative melt rates for Plume/PICOP (for the text/maybe plotting)
- [ ] check my models whether melt rate given as  ice or water
- [x] redo Fig. 2 maybe combine with suggested Fig. 3
- [x] add models to Figs. 4/5
- [ ] check Fig. 2 colorscale
- [x] make Erwin's Obs table into figure
